version: '2'
services:
  cb:
    image: nikitap/countrybank
    ports:
      - "8000:8000"
    environment:
        - CONFIG_MAIL_HOST=example@gmail.com
        - CONFIG_MAIL_PORT=123
        - CONFIG_MAIL_SMTP_AUTH=TRUE
        - CONFIG_MAIL_STARTTLS=TRUE
        - CONFIG_MAIL_USERNAME=example
        - CONFIG_MAIL_PASSWORD=passwd
    logging:
        options:
          max-size: "20m"
          max-file: "10"
